# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.Service.GameServiceModule generated by omniidl

import omniORB
omniORB.updateModule("lexilogic/utility/corbaModules.org.amalgam.Service.GameServiceModule")

# ** 1. Stub files contributing to this module
import lexilogic/utility/corbaStubs.GameService_idl

# ** 2. Sub-modules

# ** 3. End
