# DO NOT EDIT THIS FILE!
#
# Python module org generated by omniidl

import omniORB
omniORB.updateModule("lexilogic/utility/corbaModules.org")

# ** 1. Stub files contributing to this module
import lexilogic/utility/corbaStubs.GameService_idl
import lexilogic/utility/corbaStubs.PlayerService_idl
import lexilogic/utility/corbaStubs.ProgramUtilities_idl
import lexilogic/utility/corbaStubs.UIControllers_idl

# ** 2. Sub-modules
from . import amalgam

# ** 3. End
