# DO NOT EDIT THIS FILE!
#
# Python module org__POA generated by omniidl

import omniORB
omniORB.updateModule("utility.corbaModules.org__POA")

# ** 1. Stub files contributing to this module
import utility.corbaStubs.UIControllers_idl
import utility.corbaStubs.GameService_idl
import utility.corbaStubs.PlayerService_idl
import utility.corbaStubs.ProgramUtilities_idl

# ** 2. Sub-modules
from . import amalgam

# ** 3. End
