# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam.UIControllers generated by omniidl

import omniORB
omniORB.updateModule("utility.corbaModules.org__POA.amalgam.UIControllers")

# ** 1. Stub files contributing to this module
import utility.corbaStubs.UIControllers_idl

# ** 2. Sub-modules

# ** 3. End
