# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam.Utils generated by omniidl

import omniORB
omniORB.updateModule("utility.corbaModules.org__POA.amalgam.Utils")

# ** 1. Stub files contributing to this module
import utility.corbaStubs.ProgramUtilities_idl

# ** 2. Sub-modules
from . import Exceptions

# ** 3. End
