# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam.Service.GameServiceModule generated by omniidl

import omniORB
omniORB.updateModule("utility.corbaModules.org__POA.amalgam.Service.GameServiceModule")

# ** 1. Stub files contributing to this module
import utility.corbaStubs.GameService_idl

# ** 2. Sub-modules

# ** 3. End
