# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.UIControllers generated by omniidl

import omniORB
omniORB.updateModule("lexilogic.utility.corbaModules.org.amalgam.UIControllers")

# ** 1. Stub files contributing to this module
import lexilogic.utility.corbaStubs.UIControllers_idl

# ** 2. Sub-modules

# ** 3. End
