# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam generated by omniidl

import omniORB
omniORB.updateModule("lexilogic.utility.corbaModules.org__POA.amalgam")

# ** 1. Stub files contributing to this module
import lexilogic.utility.corbaStubs.UIControllers_idl
import lexilogic.utility.corbaStubs.GameService_idl
import lexilogic.utility.corbaStubs.PlayerService_idl
import lexilogic.utility.corbaStubs.ProgramUtilities_idl

# ** 2. Sub-modules
from . import ControllerException
from . import UIControllers
from . import Service
from . import Utils

# ** 3. End
