# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam.Service.PlayerServiceModule generated by omniidl

import omniORB
omniORB.updateModule("utility.corbaModules.org__POA.amalgam.Service.PlayerServiceModule")

# ** 1. Stub files contributing to this module
import utility.corbaStubs.PlayerService_idl

# ** 2. Sub-modules

# ** 3. End
