# DO NOT EDIT THIS FILE!
#
# Python module org__POA.amalgam.Utils.Exceptions generated by omniidl

import omniORB
omniORB.updateModule("lexilogic.utility.corbaModules.org__POA.amalgam.Utils.Exceptions")

# ** 1. Stub files contributing to this module
import lexilogic.utility.corbaStubs.ProgramUtilities_idl

# ** 2. Sub-modules

# ** 3. End
