# DO NOT EDIT THIS FILE!
#
# Python module org.amalgam.ControllerException generated by omniidl

import omniORB
omniORB.updateModule("lexilogic/utility/corbaModules.org.amalgam.ControllerException")

# ** 1. Stub files contributing to this module
import lexilogic/utility/corbaStubs.UIControllers_idl

# ** 2. Sub-modules

# ** 3. End
